import { randomUUID } from "node:crypto"
import { createClient, type Session } from "@supabase/supabase-js"
import { afterAll, beforeAll, describe, expect, it } from "vitest"
import {
  createCliAccessToken,
  createCliRefreshToken,
  encryptCliActorSession,
  getAuthSessionId,
  hashAuthorizationSecret,
} from "@/lib/mandala/cli-auth"
import type { Database } from "@/lib/supabase/types"
import { GET, PATCH } from "./route"

// The dedicated package script owns this local-only opt-in switch.
// eslint-disable-next-line turbo/no-undeclared-env-vars
const optedIn = process.env.RUN_CONTEXT_LOCAL_E2E === "1"
const localDescribe = describe.skipIf(!optedIn)

localDescribe("Context settings managed-CLI local Supabase E2E", () => {
  let companyId: string | null = null
  const otherCompanyId = randomUUID()
  const email = `context-e2e-${randomUUID()}@example.test`
  const password = `Context-e2e-${randomUUID()}!`
  const reason = "Local E2E verification of audited Context configuration."
  const accessToken = createCliAccessToken()
  const refreshToken = createCliRefreshToken()
  let userId: string | null = null
  let actorSession: Session | null = null

  const local = localSupabaseEnvironment()
  const admin = createClient<Database>(local.url, local.serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
  const anonymous = createClient<Database>(local.url, local.anonKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  beforeAll(async () => {
    const createdUser = await admin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
    })
    if (createdUser.error || !createdUser.data.user) {
      throw new Error(
        `context_local_e2e_user_setup_failed:${createdUser.error?.message ?? "missing_user"}`
      )
    }
    userId = createdUser.data.user.id

    const signedIn = await anonymous.auth.signInWithPassword({
      email,
      password,
    })
    if (signedIn.error || !signedIn.data.session) {
      throw new Error(
        `context_local_e2e_sign_in_failed:${signedIn.error?.message ?? "missing_session"}`
      )
    }
    actorSession = signedIn.data.session
    const actorAuthSessionId = await getAuthSessionId(actorSession)

    const company = await anonymous.rpc("create_company_with_owner", {
      p_name: `Context E2E ${randomUUID().slice(0, 8)}`,
    })
    if (company.error) {
      throw new Error(
        `context_local_e2e_company_setup_failed:${company.error.message}`
      )
    }
    if (
      !company.data ||
      typeof company.data !== "object" ||
      Array.isArray(company.data) ||
      typeof company.data.id !== "string"
    ) {
      throw new Error("context_local_e2e_company_setup_failed:invalid_response")
    }
    companyId = company.data.id

    const cliSession = await admin.from("cli_sessions").insert({
      access_token_hash: hashAuthorizationSecret(accessToken),
      refresh_token_hash: hashAuthorizationSecret(refreshToken),
      actor_auth_session_id: actorAuthSessionId,
      actor_session_ciphertext: encryptCliActorSession(actorSession),
      user_id: userId,
      selected_company_id: companyId,
      scopes: ["workspace:control"],
      client_name: "Context local E2E",
      client_version: "0.0.8-e2e",
      client_platform: "local-test",
      access_expires_at: new Date(Date.now() + 10 * 60_000).toISOString(),
      refresh_expires_at: new Date(Date.now() + 24 * 60 * 60_000).toISOString(),
    })
    if (cliSession.error) {
      throw new Error(
        `context_local_e2e_cli_session_setup_failed:${cliSession.error.message}`
      )
    }
  }, 30_000)

  afterAll(async () => {
    // Cleanup is intentionally limited to IDs generated by this test.
    const cleanupErrors: string[] = []
    const sessionCleanup = await admin
      .from("cli_sessions")
      .delete()
      .eq("access_token_hash", hashAuthorizationSecret(accessToken))
    if (sessionCleanup.error) cleanupErrors.push(sessionCleanup.error.message)
    if (companyId) {
      const companyCleanup = await admin
        .from("companies")
        .delete()
        .eq("id", companyId)
      if (companyCleanup.error) cleanupErrors.push(companyCleanup.error.message)
    }
    if (userId) {
      const userCleanup = await admin.auth.admin.deleteUser(userId)
      if (userCleanup.error) cleanupErrors.push(userCleanup.error.message)
    }
    if (actorSession) await anonymous.auth.signOut()
    if (cleanupErrors.length > 0) {
      throw new Error(
        `context_local_e2e_cleanup_failed:${cleanupErrors.join("|")}`
      )
    }
  }, 30_000)

  it("authenticates the managed CLI and reads initial server state", async () => {
    if (!companyId) throw new Error("context_local_e2e_company_missing")
    const initial = await GET(contextRequest(companyId))
    expect(initial.status).toBe(200)
    await expect(initial.json()).resolves.toMatchObject({
      companyId,
      provider: "off",
      sandboxEnabled: true,
      readiness: "disabled",
      configurationVersion: 1,
    })
  }, 15_000)

  it("mutates through the audited RPC and reads the result back", async () => {
    if (!companyId) throw new Error("context_local_e2e_company_missing")
    const changed = await PATCH(
      contextRequest(companyId, {
        companyId,
        provider: "supermemory",
        expectedConfigurationVersion: 1,
        reason,
      })
    )
    expect(changed.status).toBe(200)
    await expect(changed.json()).resolves.toMatchObject({
      companyId,
      provider: "supermemory",
      sandboxEnabled: true,
      readiness: "not_ready",
      configurationVersion: 2,
      providerStatus: {
        operational: false,
        status: "not_ready",
        detailCode: "provider_not_operational",
      },
      indexingCoverage: {
        status: "unavailable",
        eligibleRecordCount: null,
        indexedRecordCount: null,
        percent: null,
      },
      synchronization: {
        status: "unavailable",
        lagSeconds: null,
        lastSynchronizedAt: null,
        recentErrorCount: null,
      },
    })

    const readback = await GET(contextRequest(companyId))
    expect(readback.status).toBe(200)
    await expect(readback.json()).resolves.toMatchObject({
      companyId,
      provider: "supermemory",
      readiness: "not_ready",
      configurationVersion: 2,
    })

    const audit = await admin
      .from("context_workspace_setting_audits")
      .select(
        "company_id, configuration_version, change_kind, previous_provider, provider, sandbox_enabled, readiness, reason, actor_id"
      )
      .eq("company_id", companyId)
      .eq("configuration_version", 2)
      .single()
    expect(audit.error).toBeNull()
    expect(audit.data).toEqual({
      company_id: companyId,
      configuration_version: 2,
      change_kind: "updated",
      previous_provider: "off",
      provider: "supermemory",
      sandbox_enabled: true,
      readiness: "not_ready",
      reason,
      actor_id: userId,
    })
  }, 15_000)

  it("rejects a managed CLI request for another workspace", async () => {
    const wrongWorkspace = await GET(contextRequest(otherCompanyId))
    expect(wrongWorkspace.status).toBe(403)
    await expect(wrongWorkspace.json()).resolves.toEqual({ error: "forbidden" })
  }, 15_000)

  function contextRequest(company: string, body?: unknown): Request {
    const url = new URL("http://localhost/api/mandala/context/settings")
    url.searchParams.set("companyId", company)
    return new Request(url, {
      method: body === undefined ? "GET" : "PATCH",
      headers: {
        authorization: `Bearer ${accessToken}`,
        ...(body === undefined ? {} : { "content-type": "application/json" }),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
  }
})

function localSupabaseEnvironment() {
  if (!optedIn) {
    return {
      url: "http://127.0.0.1:54321",
      anonKey: "skip",
      serviceRoleKey: "skip",
    }
  }
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !anonKey || !serviceRoleKey) {
    throw new Error("context_local_e2e_missing_supabase_environment")
  }
  const parsed = new URL(url)
  if (
    !["127.0.0.1", "localhost"].includes(parsed.hostname) ||
    parsed.port !== "54321"
  ) {
    throw new Error(
      `context_local_e2e_refuses_non_local_supabase:${parsed.origin}`
    )
  }
  return { url, anonKey, serviceRoleKey }
}
