import {
  lstat,
  mkdir,
  readFile,
  readlink,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises"
import os from "node:os"
import path from "node:path"

const workspace = process.cwd()
const target = path.join(workspace, "apps/cli/dist/index.js")
const windows = process.platform === "win32"
const defaultBinDirectory = windows
  ? path.join(
      process.env.LOCALAPPDATA?.trim() ||
        path.join(os.homedir(), "AppData", "Local"),
      "Mandala",
      "bin"
    )
  : path.join(os.homedir(), ".local/bin")
const binDirectory = process.env.MANDALA_BIN_DIR?.trim() || defaultBinDirectory
const link = path.join(binDirectory, windows ? "mandala.cmd" : "mandala")
const windowsLauncherMarker = ":: Generated by pnpm cli:link"

void main()

async function main() {
  await mkdir(binDirectory, { recursive: true })

  if (windows) await linkWindowsCommand()
  else await linkPosixCommand()

  const pathEntries = (process.env.PATH ?? "").split(path.delimiter)
  if (!pathEntries.some((entry) => samePath(entry, binDirectory))) {
    console.log(
      `Add this directory to PATH before running mandala: ${binDirectory}`
    )
  }
}

async function linkWindowsCommand() {
  const launcher = `${windowsLauncherMarker}\r\n@echo off\r\n${quoteWindowsArgument(process.execPath)} ${quoteWindowsArgument(target)} %*\r\n`

  try {
    const existing = await lstat(link)
    if (!existing.isFile() || existing.isSymbolicLink()) {
      throw new Error(
        `${link} already exists and is not a regular Mandala launcher. Remove or relocate it before linking Mandala.`
      )
    }
    const source = await readFile(link, "utf8")
    if (!source.startsWith(windowsLauncherMarker)) {
      throw new Error(
        `${link} already exists and was not created by Mandala. Remove or relocate it before linking Mandala.`
      )
    }
    if (source === launcher) {
      console.log(`Mandala CLI is already linked at ${link}`)
      return
    }
  } catch (error) {
    if (!isMissingFile(error)) throw error
  }

  await writeFile(link, launcher, { encoding: "utf8", mode: 0o600 })
  console.log(`Linked Mandala CLI at ${link}`)
}

async function linkPosixCommand() {
  try {
    const existing = await lstat(link)
    if (!existing.isSymbolicLink()) {
      throw new Error(
        `${link} already exists and is not a symbolic link. Remove or relocate it before linking Mandala.`
      )
    }
    const existingTarget = await readlink(link)
    if (path.resolve(binDirectory, existingTarget) !== target) {
      await rm(link)
    } else {
      console.log(`Mandala CLI is already linked at ${link}`)
      return
    }
  } catch (error) {
    if (
      !(error instanceof Error && "code" in error && error.code === "ENOENT")
    ) {
      throw error
    }
  }

  await symlink(target, link, "file")
  console.log(`Linked Mandala CLI at ${link}`)
}

function quoteWindowsArgument(value: string): string {
  return `"${value.replaceAll("%", "%%").replaceAll('"', '\\"')}"`
}

function samePath(left: string, right: string): boolean {
  const normalize = (value: string) => {
    const resolved = path.resolve(value.replace(/^"|"$/g, ""))
    return windows ? resolved.toLowerCase() : resolved
  }
  return normalize(left) === normalize(right)
}

function isMissingFile(error: unknown): boolean {
  return (
    error instanceof Error &&
    "code" in error &&
    (error as NodeJS.ErrnoException).code === "ENOENT"
  )
}
